### ISSUE TITLE
Add trusted as an award for levelling up

### ISSUE THREAD

**Issue by NateKomodo** [CyberDiscovery/meta#14]
Give trusted at level ~20 or so, unless the user has been exempt from trusted for whatever reason

**Comment by NateKomodo** [comment]
So we can actually use stuff

**Comment by SSAFuze** [comment]
4.33% of the server can use #polls. This number seems rather low

**Comment by teamshortcut** [comment]
Anybody can ask for Trusted, and unless we have reason to, we'll generally give it to them, and then remove if needed. Tying it to Level roles would help if your problem is exclusivity, but it locks out people who want it but have only recently joined. To @SSAFuze's point, it may be 4.33% of the entire server, but that's not really representative of the active members. It's also not like we're locking away half the server without that role; it provides a few specialised features, that people can ask for if they want it.

**Comment by ghost** [comment]
The idea of having trusted automatically added with after level (1-5 as an idea) would work well and cut down moderation tasks. Then it can be taken away instead of muting and other such moderation issues.

**Comment by teamshortcut** [comment]
It's worth pointing out, I'm not sure how possible it is with Mee6 to assign this to levels, as it's set to only keep the highest role, and I'm not sure if we can selectively stack.

**Comment by thebeanogamer** [comment]
[Mee6](http://mee6.xyz/) can only assign one role per level boundary as far as I know, meaning that we would either have to retire the role levels, or grant the same permissions to the level roles, making revocation impossible.

**Comment by NicholasG04** [comment]
> 
> 
> 4.33% of the server can use #polls. This number seems rather low


The now lack of relevance of #polls gives me the impression that restricting it to trusted is no longer, in fact, necessary at all. I find it to be rarely used nowadays since it has been lowered in the channel list and because the admins are taking even less notice of the polls in there than they were prior!

**Comment by teamshortcut** [comment]
Closing as this cannot currently be implemented with the existing bot solutions.

**Comment by NateKomodo** [comment]
Just add a rank check to CD bot not hard
