### ISSUE TITLE
Move #polls up in the server list

### ISSUE THREAD

**Issue by Bottersnike** [CyberDiscovery/meta#16]
A large part of the appeal of using the suggestions channel for polls was that it was right up at the top. Everyone saw what you posted, and could easilly respond to it. Having it down at the bottom of the channel list means that it's just not visible. This would be fine, except it entirely defeats the point a channel that works around being visible; why use polls when you could just ask in #general? One of the first points raised by many users when this split to /meta happened was that they wished #polls was higher up that that seemed to be entirely ignored until people gave up asking because the staff team seemed to not care?

**Comment by teamshortcut** [comment]
The reason #polls has been moved down is because it doesn't fit categorically with the other channels at the top; they're for server-specific channels. #polls is right below #quotes, as a channel that is used socially (and often for jokes) but isn't related to the server, CD or other semi-educational topics. (STEM Dojo) If a question is asked in #general, it will usually get drowned out within minutes.

**Comment by ghost** [comment]
I do not see how #memes is a releavant topical issues which needs to be placed high in the server ranking. There are other channels such as #lingustics in the STEM DOJO which doesn't fit where it is. So why be different to #polls apart from trying to stop people expressing ideas.

**Comment by teamshortcut** [comment]
#memes is put with other general purpose channels, and a slightly lower position of #polls is not restricting people from expressing ideas.

**Comment by Bottersnike** [comment]
The problem I was raising was not the _expression_ of ideas, but the visibility of that expression. I could go tweet something right now, and about 2 people would probably see it ever. Likewise, I could post something in #polls and it's just not going to get nearly the same visibiliy as before. Ironically, one of the most voted on things in there is a "poll" that just ironically states `we love this system` with `FUCK NO` reacted to it.

**Comment by teamshortcut** [comment]
People manage to check the year group channels and #quotes just fine; as I said before, #polls does not fit categorically with the other (currently) uncategorisied channels.

**Comment by ThisIs0xBC** [comment]
In response to shortcut, I rarely check quotes or the year 11 channel because I have to scroll so damn far to see it. Suggestions was so good before because you could quickly see if there were any unread messages and go vote on them, I find that myself and everyone else isn't doing the same anymore with the new polls channel, as the rate of suggestions/polls has diminished dramatically (even if we don't include meme suggestions in the numbers.) I find that I rarely use or check polls compared to suggestions, just because I can't be bothered to scroll down for it, it's annoying

**Comment by teamshortcut** [comment]
Okay, that's fair. The fact remains it does not fit with the 3 uncategorised channels at the top. If it's of such importance, would it work in another category (to me, Server Stuff seems the natural fit, hence its current position), or perhaps a better solution would be adjusting the current category rankings?

**Comment by ThisIs0xBC** [comment]
To be honest, I don't care how it happens, as long as it happens.

**Comment by teamshortcut** [comment]
_paging @Bottersnike_

**Comment by teamshortcut** [comment]
Adjusting the Server Stuff category would probably be my preferred solution, though if you can justify #polls going in another category I'm happy to consider that too.

**Comment by Bottersnike** [comment]
What about moving the whole Server Stuff group up slightly in the channel list? All the channels in there seem like they would probably benefit from more of a profile in the channel list.

**Comment by teamshortcut** [comment]
Seems a good solution to me. Perhaps just above the 100 Percent category? @Bottersnike

**Comment by Bottersnike** [comment]
Yeah that feels like it'd work

**Comment by teamshortcut** [comment]
Resolved by #213
