### ISSUE TITLE
Moving meta-related files from cyberdisc-bot

### ISSUE THREAD

**Issue by fractalpenguin** [CyberDiscovery/meta#2]
There are files in [CyberDiscovery/cyberdisc-bot](https://github.com/CyberDiscovery/cyberdisc-bot) that should be moved here, for the following reasons:

- .security.txt/SECURITY.md: Security policies regarding bugs in code affect not just the bot, but every community repository.

 - CODE_OF_CONDUCT.md: Likewise, a code of conduct would be applicable to all projects, and not just the Discord bot.

**Comment by picapi** [comment]
Just as a note, I feel we need to ensure their existence and continued adoption is still clear on any repositories that they apply to if we decide to move these files.

**Comment by thebeanogamer** [comment]
Honestly, I think this makes more sense to leave in the individual repos.

**Comment by jerbob** [comment]
same

**Comment by fractalpenguin** [comment]
I mean, they're pretty irrelevant to the code itself, but more in terms of best practices.

**Comment by thebeanogamer** [comment]
On the code of conduct part, we will keep it within the respective repos, so that GitHub directs new contributors to review it before contributing:
![image](https://user-images.githubusercontent.com/3729048/57235422-bd5d9c00-701a-11e9-89df-9186e0c251b9.png)

With the security files, we want them to be included if the repo is ever cloned, without referring to a separate file.
