### ISSUE TITLE
Upvote/Downvote Reactions in #meta channel

### ISSUE THREAD

**Issue by AdamBromiley** [CyberDiscovery/meta#20]
Have the bot to auto-add upvote/downvote emojis to **Issue Opened** messages in the #meta Discord channel.

Not many people on the server actually use GitHub, can be bothered to go on here and comment, or actually know how to use GitHub. Adding reaction emojis in the channel will allow mods to quickly gauge the community's views on a suggestion, much like the old #suggestions, whilst still having the ability to make the final say in things and discuss them further on here. On here it is very much a few people contributing to changes affecting 1000 people, whereas it used to be upwards of 40 people.

**Comment by picapi** [comment]
I agree that it's a good idea to give the silent majority an opportunity to have a say without too much extra hassle - although sometimes reactions result in somewhat of a bandwagon effect where people may upvote something because other people have...

As a note, this would require a PR to be made to the bot in order to implement the reactions.

**Comment by teamshortcut** [comment]
You misunderstand the system @AdamBromiley. (which, as it's only just opened, isn't entirely unreasonable) Issues are meant for problems people have, if you have a suggestion/improvement, you should make a PR, and approved PRs _will_ go into #meta for voting, exactly as you say. As it is, I'm closing this, as really it should be a PR anyway.
