### ISSUE TITLE
Unban Dave

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#204]
Dave was banned a long time ago. Permanent bans serve no purpose; we all know that Dave has alts, and, with all the due respect to the Mod team, trying to ban them all would be fruitless. In his [Open Letter To CD](https://docs.google.com/document/d/1uE4YBW2pJPk7Cm5l4TaRdR5aY0JaeuSDwYcXG1YLg8c/edit), I believe he makes some excellent points about bans and highlights some issues, and has been ignored by the admins. Personally, I, and others, believe that Dave should be given a second chance, and unbanned.

**Comment by SSAFuze** [comment]
I would agree that permanent bans have no place. The open letter clearly shows that he is regretful of his actions, and it is foolish to keep people banned due to mistakes which they now seek to redeem themselves for. The letter also suggests that he is willing to work with with the server and the mods to sort out issues with the server (which is required). I don't personally know Dave but the brief interactions i have had with him suggest he isnt a threat to the server.

**Comment by teamshortcut** [comment]
Bans are the moderators' responsibility; Dave remains banned as his actions do not reflect those of our community, and he is not somebody we want a part of it.

**Comment by NicholasG04** [comment]
The fact that this has been closed without giving the opportunity for community discussion disgusts me. I question the point of meta if decisions are to be made like this.

**Comment by ThisIs0xBC** [comment]
I knew this would be closed before it got interesting. Shortcut doesn't want to discuss it so abuses the fact that he can just close the issue before people can properly discuss it. This was mentioned in Dave's letter, the mods run away from things they don't want to handle, in this case they just close the issue. With the polls channel, when people were saying "Should polls be moved up near to the meta channel" the messages got deleted. This happens with everything the mods don't agree with, they just delete any evidence of it being there and move on and it pisses me off. Seriously, can the moderators PLEASE actually address the community's complaints and do something about them, instead of burying their heads in the sand like they normally do.
