### ISSUE TITLE
Emoji Suggestions!

### ISSUE THREAD

**Issue by lightspeedana** [CyberDiscovery/meta#232]
# New Emoji Suggestions!

### Having now reached Nitro Boost Level 1, it's up to the community to suggest and upvote new emojis for our 50 new slots!
If you have an emoji suggestion, add it in the comments below as well as its name, and we can then PR and vote on appropriate ones. Please make sure they all fit our rules and don't have any NSFW or discriminatory content! 

Enjoy 😄 We look forward to seeing new suggestions!

**Comment by ghost** [comment]
:somewhatthis:

**Comment by lightspeedana** [comment]
@Robertgold you need to give an actual image for it...

**Comment by maishams** [comment]
hello please add my :smiley~1: thanks https://cdn.discordapp.com/emojis/581910891826774079.png?v=1

**Comment by maishams** [comment]
^ i think you should add it because i drew it and its a cool emoji and it is very cool and i would use it a lot and i like it and its good

**Comment by NateKomodo** [comment]
im removing my nitro boost :P

**Comment by NicholasG04** [comment]
lol I see no level 1 boost

**Comment by lightspeedana** [comment]
@thebeanogamer big blue B for :beano: please as per popular demand
If there's one for @teamshortcut only fair the B gets justice

**Comment by AdamBromiley** [comment]
Ban hammer emoji, either the one with a blob holding it or just the hammer. I'll link it when I've finished cooking.

**Comment by AdamBromiley** [comment]
Also the Cyber Discovery logo, it's only fitting.

P.S. if anyone wants more of the Agent J blob emojis I can send over the .SVG files, I haven't got a program to edit them anymore

**Comment by NateKomodo** [comment]
I should get an emoji bc I boosted

**Comment by Sh3llcod3** [comment]
Hello all,

**The emote suggestions are inbound so hold your breath and put on your [stealth suit](https://ubistatic19-a.akamaihd.net/ubicomstatic/en-GB/global/media/scbl_ss5_full_164163.jpg).**

First of all, I suggest the Azure Devops emotes, so we can celebrate our inner Microsoft desires:

<p align="center">

<a href="https://avatars2.githubusercontent.com/ml/1303?s=140&v=4">
<img src="https://avatars2.githubusercontent.com/ml/1303?s=140&v=4" width="128px">
</a>

<a href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNWD1cxTQcBx9kX9S4osIu0w5LnRYps-93a4yoiVgnK4Zeh9FLFw">
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNWD1cxTQcBx9kX9S4osIu0w5LnRYps-93a4yoiVgnK4Zeh9FLFw" width="128px">
</a>

<a href="https://wem.technology/wp-content/uploads/2018/06/Azure-logo.png">
<img src="https://wem.technology/wp-content/uploads/2018/06/Azure-logo.png" width="128px">
</a>

<a href="https://logo.clearbit.com/azure.com">
<img src="https://logo.clearbit.com/azure.com" width="128px">
</a>

<a href="https://cloud.google.com/_static/images/cloud/products/logos/svg/kubernetes-engine.svg">
<img src="https://cloud.google.com/_static/images/cloud/products/logos/svg/kubernetes-engine.svg" width="128px">
</a>

</p>

Then, I suggest ~~the entirety~~ some of the Google Blob emotes since they are absolutely adorable and invokes emotions which cannot be described by any tangible feeling. Here are some nominations, some of them used to exceed the emote file size, but I have compressed them on my local machine it should fit. I have done some research and found out that Discord's max Emote size is 256kb, so I have tried to keep it within that.

<p align="center">
<a href="https://discordemoji.com/emoji/6287_bloblserverboost">
<img src="https://discordemoji.com/assets/emoji/6287_bloblserverboost.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/1429_BlobAstronaut">
<img src="https://discordemoji.com/assets/emoji/1429_BlobAstronaut.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/7491_communistflagblob2">
<img src="https://discordemoji.com/assets/emoji/7491_communistflagblob2.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/8156_okay_blob">
<img src="https://discordemoji.com/assets/emoji/8156_okay_blob.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/piingblob">
<img src="https://discordemoji.com/assets/emoji/piingblob.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/blobwave">
<img src="https://discordemoji.com/assets/emoji/blobwave.png" width="128px">
</a>

<a href="https://drive.google.com/file/d/19yl17RMPaBOAAxMtnXybpw078zTXWoCJ/view?usp=sharing">
<img src="https://drive.google.com/thumbnail?id=19yl17RMPaBOAAxMtnXybpw078zTXWoCJ" width="128px">
</a>

<a href="https://discordemoji.com/emoji/7337_pingthink">
<img src="https://discordemoji.com/assets/emoji/7337_pingthink.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/7872_blob_hero">
<img src="https://discordemoji.com/assets/emoji/7872_blob_hero.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/IdeaBlob">
<img src="https://discordemoji.com/assets/emoji/IdeaBlob.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/blobfear">
<img src="https://discordemoji.com/assets/emoji/blobfear.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/blobsaluteban">
<img src="https://discordemoji.com/assets/emoji/blobsaluteban.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/5279_BlobNoBully">
<img src="https://discordemoji.com/assets/emoji/5279_BlobNoBully.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/BlobCouncil">
<img src="https://discordemoji.com/assets/emoji/BlobCouncil.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/hypeblob">
<img src="https://discordemoji.com/assets/emoji/hypeblob.png" width="128px">
</a>

</p>

Aside from Blob Emotes here are other suggestions.

<p align="center">

<a href="https://drive.google.com/file/d/11gBPsIWCPWm_EqnvoFXeVNaS6k2VbLqx/view?usp=sharing">
<img src="https://drive.google.com/thumbnail?id=11gBPsIWCPWm_EqnvoFXeVNaS6k2VbLqx" width="128px">
</a>

<a href="https://drive.google.com/file/d/1Rjif1hbZ0kCYJujjUyoUjdCxUdvM9YML/view?usp=sharing">
<img src="https://drive.google.com/thumbnail?id=1Rjif1hbZ0kCYJujjUyoUjdCxUdvM9YML" width="128px">
</a>

<a href="https://drive.google.com/file/d/1s3MDzVUMp3dZBE7oKs-dtuXx1mGXrAbs/view?usp=sharing">
<img src="https://drive.google.com/thumbnail?id=1s3MDzVUMp3dZBE7oKs-dtuXx1mGXrAbs" width="128px">
</a>

<a href="https://discordemoji.com/emoji/1011_DiscordController">
<img src="https://discordemoji.com/assets/emoji/1011_DiscordController.png" width="128px">
</a>

<a href="https://discordemoji.com/emoji/5408_pikadab">
<img src="https://i.redd.it/0i21ur4fl1x11.png" width="128px">
</a>

</p>

Please feel free to add as many or as little of them as you like, the name should be available when you click the images, they should take you to the place to download them from.

@thebeanogamer @lightspeedana What do you think?

**Comment by NateKomodo** [comment]
i fucking love azure cognitive services, you cant diss them

**Comment by Trefonix** [comment]
![The_Puzzler](https://user-images.githubusercontent.com/41169525/59051966-f42b0a00-8885-11e9-8e7e-655c00d8623c.png)
:beano:

**Comment by Sh3llcod3** [comment]
I think that would fall under disturbing, and the comedic factor has been driven out by it being spammed in chat. You should consider deleting this @Trefonix

**Comment by ghost** [comment]
I do agree on the ducks being implemented, if someone could make :somewhatthis: I would also support their bid.

**Comment by Sh3llcod3** [comment]
@Robertgold You mean Blobs? or Ducks?

**Comment by Trefonix** [comment]
![image](https://user-images.githubusercontent.com/41169525/59054413-8a156380-888b-11e9-9132-92c97e12c33b.png)
:verythis:

**Comment by Trefonix** [comment]
![image](https://user-images.githubusercontent.com/41169525/59054457-a7e2c880-888b-11e9-9e80-705e7b8d6fde.png)
:somewhatthis:

**Comment by ghost** [comment]
Blobs and ducks looks the same I call it whtat I want and good work @Trefonix

**Comment by Bentechy66** [comment]
:evilpatrick: - https://cdn.discordapp.com/emojis/438980827133771778.png?v=1
:facepalm: - https://cdn.discordapp.com/emojis/438980669503176705.png?v=1

**Comment by Sh3llcod3** [comment]
Ok, so I've finalised my list of emotes to submit, if someone like @lightspeedana or an admin could review these, then that'd be great. :100:

**Comment by teamshortcut** [comment]
Thanks all for the suggestions. As things currently stand, we have 2 boosts, one of which will expire next month. (5th July if I'm remembering correctly) As a result, my inclination would be not to add emojis until we have another boost, or we'll be adding them only to lose them within a couple of weeks. However, the more suggestions for when we reach that point the better! Is that a call for :ana: I hear from the back...

**Comment by thebeanogamer** [comment]
We are currently at 51, `:beano:` is not in the file, but one will need to be removed as our restriction will soon return to 50.

**Comment by thebeanogamer** [comment]
_Unless 2 people want to boost_

**Comment by Sh3llcod3** [comment]
I've final-finalised the emote suggestion list. Shame to see that we will lose the capacity. *This ain't it chief*

**Comment by NicholasG04** [comment]
Actually, you could add them in now and all that will happen is that they cannot be used until reboosted....

**Comment by lightspeedana** [comment]
I think discussion of this has moved to the server itself, and now suggestions are more suited to PRs (wow this is sad, it's my own issue too!). But thanks everyone for all your input! 😄
