### ISSUE TITLE
Unban Chiv

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#245]
# Unban Chiv
*I swear this isn't another unban dave campaign ok?*

### *A description of the issue:*
The reason chiv was banned was because he doxed sai, sai has now forgiven chiv for the doxing and thus in my opinion he should be unbanned.

### *Proposed Solution:*
unban chiv

**Comment by Bentechy66** [comment]
proof sai supports: ![image](https://user-images.githubusercontent.com/19192864/60461313-12deaf80-9c3e-11e9-9288-4cf42ba8d952.png)

**Comment by Bvzty** [comment]
Lmfao I am chiv, just to put in my part, I didn't actively search for documents on Sai to expose him, as the word "dox" suggests, I legit was with him in person, took a pic of him, and sent it. And as a result I was banned. Sai doesn't seem to give a shite about the pic/"dox". Ty

**Comment by teamshortcut** [comment]
Fair enough that Sai has personally forgiven Chivato; however, that doesn't erase what he did, nor change our rules. That's important because, if nothing else, it hardly inspires confidence he won't continue to break those rules in future. His actions outside of the CD server, on many occasions, would either directly break our rules or be behaviour we would encourage among our members. (I can back that up with screenshots, but they're not pleasant so I'd rather not) We've stated previously that bans are an administrative decision, and are not the point of purpose of the meta repo. I will also finally point out that, besides our own personal concerns, he is also on the infosec shared banlist we are a part of anyway. 
![image](https://user-images.githubusercontent.com/12185328/60461659-17f02e80-9c3f-11e9-8ae9-137de3c262bb.png)

I'll leave this open for discussion for a short time, but this isn't really an issue for meta, and we do not plan to unban Chivato for the reasons above.

**Comment by Bvzty** [comment]
Lmfao this issue was already cleared and the only thing that could be considered correct was the "ableist" point. I am going to discuss this with cavevenom now, since I can clearly see he was the one to report this (When I was an admin on hackthebox I turned him down for the mod position so he may have been a bit salty). I would also like to remind you that a lot of people in the community would like to see me banned, so to actually make sure the messages are from me, I would appreciate it if you verified the messages to make sure they were not made with inspect element (CTRL + SHIFT + i in discord) or with photoshop. :)

**Comment by teamshortcut** [comment]
There were other people who brought it up in the shared banlist, and I certainly won't be considering any doctored screenshots.

**Comment by Bvzty** [comment]
Yes, but you don't know what is doctored and what isn't, that is my point. The CD staff are not the only ones with vendettas against me. And it is funny how the only server that banned me was CD (for these reasons), even though the banlist is shared with TMHC, HTB and JHD (to my knowledge), cavevenom being an admin ON JHD, and I am not even banned from there. If you do not want to unban me, then so be it, but do not spread false information about me being racist or sexist, I will not stand for it.

**Comment by teamshortcut** [comment]
The banlist is shared with a variety of servers (I can pull a list if you really want), TMHC, HTB etc. seemingly have chosen to ignore this particular case; you'd have to ask their admins why that is, it doesn't change CD's decision to abide by the banlist. The accusations of racism and sexism didn't come from me, but they came from a partnered server and I have no reason to disbelieve them, particularly given the things I have personally seen you say. (off the top of my head, homophobic slurs)

**Comment by Bvzty** [comment]
just seems a bit fishy, whether you decide to agree or not, out of the WHOLE list of servers, including the one that accused me, CD is the only one who decides to follow up these accusations with a ban

**Comment by Bottersnike** [comment]
@teamshortcut Is the any posibility of actually getting said messages? Because it looks from that screenshot like it's just someone saying "X is a racist, sexist, arsehole", so either:
- they didn't provide proof and you banned from that
- they did provide proof but it has no sustinance and so it wouldn't back up your argument to post it, or
- you're going to reply to this thread with the proof

**Comment by Bvzty** [comment]
Any screenshots of messages are irrelevant, since they can be fabricated in a matter of minutes, this is why I am requesting they get verified.

**Comment by teamshortcut** [comment]
I'm not sure how I'm meant to "verify" screenshots, I can try and dig for some if you want but it doesn't seem like it would be accepted anyway...

**Comment by Bottersnike** [comment]
If shortcut was to go and retreive a first-hand screenshot of something such as a raw message or a dyno deletion log, I'd trust he hadn't faked it; a 2nd hand screenshot, I absolutly agree with chiv, is not trustworthy nor valid for a ban.

**Comment by Bvzty** [comment]
I mean don't send any screenshots unless they are verified by discord to be authentic.

**Comment by Bvzty** [comment]
@Bottersnike as I previously stated, anyone can CTRL SHIFT i and change the message. Even if it is on a dyno bot or whatever. I don't even care about being unbanned. I just want the accusations to be cleared.

**Comment by teamshortcut** [comment]
For the sake of transparency, the screenshotted infosec partner has since later stated in DMs to Chivato that he has no warnings in their server for racism or sexism, nor do I have direct evidence to suggest Chivato is either sexist or racist, or ableist besides his repeated (albeit commonplace) use of "austistic" or "retarded" in a negative context. For the sake of further transparency, I do have direct evidence of useage of homophobic slurs, which would in some cases be enough for a ban in CD alone.
![image](https://user-images.githubusercontent.com/12185328/60464368-49202d00-9c46-11e9-8385-b2d986e88072.png)

As I've said previously, we will not be unbanning Chivato, but that should clear up the basis for "accusations".

**Comment by Bvzty** [comment]
This was a mistake, I should not have said it, and I apologise.

**Comment by Bvzty** [comment]
![Screenshot from 2019-07-01 21-34-15](https://user-images.githubusercontent.com/46692247/60465303-b208a480-9c48-11e9-97c9-322da69760c8.png)
I am also going to post this for transparency (This is a conversation with the user that stated I was racist, sexist and ableist).

**Comment by ZomBMage** [comment]
i call bs on two chivatos

**Comment by Bvzty** [comment]
@ZomBMage I agree, it is fishy. He may be trying to cover up a previous mistake, but I don't mind as long as he says it wasn't me. I can verify that I have not touched this screenshot or modified it by calling you and sharing my screen.

**Comment by ZomBMage** [comment]
It's not the integrity of the screenshot that came to mind rather than perhaps saying "can you say that there was another" then deleting that message. Besides from that, if you have matured past offensive comments (malicious intent or otherwise) then fair enough

**Comment by Bvzty** [comment]
@ZomBMage I am sure he is willing to say in a call that I have not said or done anything to change his opinion... I don't know what else I can do honestly. At the end of the day, none of this can be verified, and people may have their doubts, I just ask that false accusations do not be made.

**Comment by teamshortcut** [comment]
I think this has gone past the point where it's productive, as the original issue has been answered.
