### ISSUE TITLE
Allow technically adults access to #year13

### ISSUE THREAD

**Issue by Alpheeexx** [CyberDiscovery/meta#263]
# Title Of Issue

### *A description of the issue:*
Many year 13's are starting to look at uni's/future paths. It would be useful if those who have already done this had an area to pass on knowledge. Rather than creating a new channel. Allow them to access #year-13

### *Proposed Solution:*
Allow technically adults role to access #year-13

### *Additional Comments:*
[fill out]

**Comment by AdamBromiley** [comment]
Last year we held a vote in the year 13 channel in favour of it. Personally I think it'd be beneficial for year 13s to gain insight into different universities and pathways from people already in the system. Right now these discussions seem to flood #general purely because there's nowhere else to ask.

**Comment by lightspeedana** [comment]
I think this is more suited to a PR, which we can then vote for, and whilst I'm closing this issue from inactivity, this is something that could easily happen. I am all for this 😄
