### ISSUE TITLE
No hints past challenge 8

### ISSUE THREAD

**Issue by incarnadined** [CyberDiscovery/meta#265]
# No hints past challenge 8

### *A description of the issue:*
New members of the server seem to be constantly asking for help on challenges beyond 8, just for someone to respond to them saying they can't give hints that high.

### *Proposed Solution:*
Create an auto-response with the CD bot that when certain words are mentioned (hint, help, 8, 9, 10, 11, 12 etc.) it quotes the pinned no hints message or simply states the rule.

### *Additional Comments:*
None

**Comment by teamshortcut** [comment]
Just for context, that cutoff was requested by official CD staff last year. 
![image](https://user-images.githubusercontent.com/12185328/64925221-4e245f80-d7e5-11e9-88ea-fc21cb7a1b36.png)
I'm not sure how much the bot would help rather than just be an annoyance, particularly given the `:assess` command will provide a warning for any challenges higher than 8, which is then just ignored, but if it could be done in a non-instrusive way then maybe it could help for new members.

**Comment by AdamBromiley** [comment]
May I add an urge to make responses a bit more friendly too. I've noticed, and I understand why, some people are getting irritated with the amount of hint requests, but at the end of the day the whole point of CD is to be educational and get people into cyber (which is hard when you join a community, innocently ask for help and get shutdown). Consider that without completing 8 and above you don't get into Game, which ultimately is the biggest learning experience of the course. It'd be a shame if someone misses out on it and forever be trapped in assess year after year.

Maybe if we take in the context (say you know the person has been struggling for a few hours and described what they've attempted and such) and then give a small push in the right direction. Not explaining the solution, but something as simple as "maybe look at what can make a simple HTML/CSS dynamic and responsive, then see how you can manipulate the responses". To many people that's obviously describing JS and using the Console, but to a newbie it gives just enough so they *know what to Google* without giving away a whole solution.

This is coming from someone who, I can safely say, wouldn't be about to start a cybersec degree if I didn't get into Game in 2017. And how I got into Game was majorly my own intuition in Assess, but **definitely** not without benefitting from a friendly, proactive, and educational community.

**Comment by ThisIs0xBC** [comment]
^ What Adam said! So many people are just utter pr!cks to new members (me included, sometimes, although I try really hard to be nice and help people out)

But in my opinion, people shouldn't be so strict on the "no hints past challenge 8" rule. I think they should just tone the hints down a lot. For example, my go to hint on C14 when people ask is just
"Networking
API Calls"
to push them in the right direction. I then always say something along the lines of "That's all I will say for now, if you need some more pointers further down the line just message me 👍 ". I think that's perfectly fine (especially if you DM the person.)

Overall, stop being such knobs to newcomers please and thanks

**Comment by jb3** [comment]
> Create an auto-response with the CD bot that when certain words are mentioned (hint, help, ***8, 9, 10, 11, 12*** etc.) it quotes the pinned no hints message or simply states the rule.

Hello I have just invested in 8 beanocoins.

**Comment by lightspeedana** [comment]
Considering this could incur bot spam, and the issue has been fairly inactive, I think we can safely conclude that it's more of an attitude problem than something we can necessarily fix. Good ideas here though, we can definitely be friendlier, but I think perhaps a bot command would not really help, especially since we're now almost done with assess and doing this for game would be overly complex. 😄
