### ISSUE TITLE
Server meta is purposefully difficult to lodge complaints leading to stagnation

### ISSUE THREAD

**Issue by stvhx** [CyberDiscovery/meta#275]
### *A description of the issue:*

Currently meta issues are done through github issues which is relayed via a github webhook to the discord.  This is a slow feedback loop which could be more efficient.
I’ve also found that meta issues often take place in other channels so centralising it would be good.

### *Proposed Solution:*

Open up the meta channel to where "trusted members" can discuss topics. This could lead to a more community-based server due to the increased participation.

### *Additional Comments:*

Removal of the "trusted" role can serve as punishment for abusing the meta channel.

**Comment by SSAFuze** [comment]
I would like to preface this message by saying how I share your desire for a community-based server. The server should be the very best that it can be for all of it's members. But now I would like to address your issue. 

I personally feel that you are exaggerating how challenging it is to make a meta issue. For a cybersecurity related server, its not unreasonable to expect many members to have a GitHub account. From there, its's a simple process of creating an issue and laying out your point (which it seems you did with great success). 

> more an authoritarian system

I'm not entirely sure what you mean by this. The staff team has always, and will always, listened to the community and considered their opinions carefully. If I have not understood the point here, please let me know.

> I’ve also found that meta issues often take place in channels such as overflow

Again not entirely sure what you mean here. The staff have had conversations with other members in channels on the server which have been very informative. But good discussion has also taken place on this repo, with several key changes being discussed here.

> Open up the meta channel

Or as discussed above, if people feel strongly about an issue, they can create an issue/comment on this repo. Much informal discussion also occurs in other channels on the server which can help to more casually work through ideas before hopefully discussing them here.

> This would bring the server out of a stasis allowing for a more community-based server.

This is a key point that I do wish to address. Firstly, I would be interested to hear what you mean by the server being in a stasis? It seems like a fairly active and vibrant community to me. You also seem to imply that the community isnt listened to. The entire purpose of this repo is to give a location for focused and meaningful discussion around server related requests and issues. The staff team also listens to members during casual conversations on the server and I can say that we do listen to them. If I may, I would like to throw out an idea I have had to conclude: is a lack of discussion on this repo perhaps a sign that there isnt much change desired rather than it being too complex to use?

Please don't hesitate to query anything that doesn't make sense (I have just sort of spitballed some ideas), and please do let me know what you think of my points. Also, if you think I have failed to address something, let me know. Additionally, I would be interested to get the perspective of others.

NOTE: this message is my own and does not necessarily reflect the view of the entire staff team. I also invite them to provide a contribution if they wish.

**Comment by AlphexGaming** [comment]
Hot.

**Comment by Bentechy66** [comment]
ok boomer

**Comment by AlphexGaming** [comment]
be quite zommer. Let the boomers talk

**Comment by Bottersnike** [comment]
It's worth noting that this repository does tend to function significantly better when using an account that at least has some indication of your in-Discord name, or at the least signing off your message, rather than the joyride that is linking an unknown account making a complaint back to the discord user associated with it :)

**Comment by IlleQuiProgrammat** [comment]
@Bottersnike this is the exact reason why Github Issues are bad—they’re separated and can lead to doxing which is a major issue.

**Comment by ghost** [comment]
The system is fine it takes 3 minutes to make a GitHub account. Sure issues might be discussed in other channels but if one feels strong enough they will post it in here. @IlleQuiProgrammat if doxing is an issue you could just make a separate Github account on a secondary browser and it then can't be traced back to you.

**Comment by IlleQuiProgrammat** [comment]
@SSAFuze 
> I'm not entirely sure what you mean by this. The staff team has always, and will always, listened to the community and considered their opinions carefully. If I have not understood the point here, please let me know.

Yes I’m sure they have but there is still a great centre of power and control which has been used in their own interest at times doesn’t quite sit right in such a server.. how can server staff gauge the desire for a feature if they are unable to see direct support on the server.. I mean who actually checks #meta after comments are published etc etc?

> Again not entirely sure what you mean here. The staff have had conversations with other members in channels on the server which have been very informative. But good discussion has also taken place on this repo, with several key changes being discussed here.

Yes, it has but do you not agree that a dedicated meta channel fits much better than #maths per se? Those channels do also have other interruptions.. you are also acknowledging the fact here that it is entirely possible to have #meta open to discord discussions as it is with *much* larger servers.

> they can create an issue/comment on this repo

That is avoiding the issues at hand, I’m sorry. Another point is of doxing which I’ve addressed above.

> I would be interested to hear what you mean by the server being in a stasis?

There has been little change and, from what I’ve experienced, meta issues have often been shut down despite genuine desire and often need for channels among others.

> is a lack of discussion on this repo perhaps a sign that there isnt much change desired rather than it being too complex to use?

No. I’ve seen many a time when suggestions which are supported by a *bunch* of people but it never goes through to the issues stage as for previously addressed reasons.

I’d also like to ask what issues exist opening up the meta channel?

**Comment by IlleQuiProgrammat** [comment]
@H4ckerJ4cker

> The system is fine it takes 3 minutes to make a GitHub account. Sure issues might be discussed in other channels but if one feels strong enough they will post it in here. @IlleQuiProgrammat if doxing is an issue you could just make a separate Github account on a secondary browser and it then can't be traced back to you.

That is an incredibly useless comment, I’m sorry.

> you could just make a separate github account

Keep in mind this would require much more than 3 minutes as I would need to set up an email account with a reputable provider (I believe that’s the requirement now but I’m unsure) which takes time at first and you also say install another browser.. .thats gonna be a bunch of time..
Then I need to sign up to github, go here and submit.

Not exactly an easy, quick process is it?

> if one feels strong enough they will post it in here

Yes, but how does one discuss this properly without a #meta channel?
Answer: they cannot
And again, obviously, the same issues arise..

It’s slightly late so apologies for any bad grammar/spelling.

**Comment by Bottersnike** [comment]
The meta channel just allows people to see as new issues and PRs are opened. Suggesting opening it because "you can" is the same as suggesting the polls channel or the social channel are opened. As it is, I've seen far more structured conversations that have actually lead to things happening going on in this repository than I saw exploding debates that were ever resolved with a favourable outcome. The fact it's a tad harder to post here than in a channel is, imo, a good thing because it acts as a small gatekeep to stop people who don't actually have anything valid to suggest, and are just suggesting for suggesting's sake. Doxing really isn't a problem, honestly. It's just as much as a problem as me logging into the discord server with my `<REDEACTED>` account, which would instantly give away all my personal details, what with being a personal account for personal things. If you have a personal account on a site like discord or github, you really should either embrace people knowing who you are (and control what they know (example: what eo does)), or you should make a private account too. In regards to who checks #meta, well.. I mean.. that's the fault of anyone not checking it? It's far more visible than a wall of some 2000-3000 messages that nobody can be arsed to scroll though.

**Comment by SSAFuze** [comment]
@IlleQuiProgrammat 

![image](https://user-images.githubusercontent.com/43763221/66350109-5853fc80-e952-11e9-90b9-40d099eede4f.png)
![image](https://user-images.githubusercontent.com/43763221/66350133-67d34580-e952-11e9-8cd1-2be1e0b3207d.png)

Just as a little taster, here are some polls done based off meta issues, I am sure you'll note the fairly significant numbers of votes. These are examples of times which the staff team implemented change based off meta issues (and there are more).

You talk of a dedicated meta channel and how proper discussion cant occur here. May I point to this very issue where we appear to be discussing this very constructively. Whilst it may be mildly inconvienient, there are ways to protect your OPSEC such as a new account (see messages from @Bottersnike). 

I'm not entirely sure what else I need to add, but again please do let me know what you think.

**Comment by lightspeedana** [comment]
This issue has now been fairly inactive, and whilst there are valid ideas and concerns present here, I think that the meta repository is fair, democratic and functioning just fine. The community is as vibrant as ever and I don't think anything is changing that whatsoever 😄
