### ISSUE TITLE
Unban Dave

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#276]
(Copy of #204 which was closed without allowing for discussion, which quite frankly I find disgusting, this repo is supposed to be where the staff "Listen to the community", but that's an issue for another time)

 Dave was banned a long time ago. Permanent bans serve no purpose; we all know that Dave has alts, and, with all the due respect to the Mod team, trying to ban them all would be fruitless. In his [Open Letter To CD](https://docs.google.com/document/d/1uE4YBW2pJPk7Cm5l4TaRdR5aY0JaeuSDwYcXG1YLg8c/edit), I believe he makes some excellent points about bans and highlights some issues, and has been ignored by the admins. Personally, I, and others, believe that Dave should be given a second chance, and unbanned.

**Comment by Bottersnike** [comment]
Have had some great interactions with him in that CD scribbl game the other day he joined. 10/10 would recommend.

**Comment by Trefonix** [comment]
I support a policy of timed bans and a general amnesty on bans over 6 months old.

**Comment by SSAFuze** [comment]
Please correct me if I'm wrong, I believe that Dave (the focus of your issue) has expressed that he wouldn't return to the server even if he was unbanned. If this is the case, why are you seeking a reversal of his ban?

**Comment by DefinitelyNotDave** [comment]
Yes, it is unlikely I would return to the server if I was unbanned for reasons I expressed in my two letters to the server. However, this is avoiding the issue, if I choose to come back after an unban is entirely my decision. The reasons for my ban were very valid(I'd have banned me sooner), however that was back in November. Almost a year on, I haven't spoken to the person who was a large part of the reason I got banned in 8 months, do you really believe theres a chance of it happening again? Dabato is always cited as a reason for permanent bans, an admin will reference how he was unbanned and got banned again quickly. There's a major flaw in this argument though, I'm not Dabato. He was there almost entirely to troll and although he was a large part of the reason I was able to take over the server from Collm, he didn't really care about helping the community. I'm friends with Dabato but we're very different people and using his case as a reason to not unban me doesn't make any sense. I talk to a lot of the active people in the server, even though I'm banned I'm still an active member of the community. All the mods seem fine with me lurking on an alt, screenshotting a message and then dming the person, so why is it such an issue for me to respond in the same text channel that they sent their message in? The fact I have very little interest in joining back also means I have no interest in any drama, I made the new server to avoid drama and I hate that I became the main source of it for a while. Everyone knows I don't get on with beano and shortcut, I hold no grudge against either of them however I don't think the inverse is true, I stand by a lot of what I said about how they run(or ran) the server(although I will apologise for any personal attacks I may have made, they were unnecessary and immature) however if this is an issue then it shows that my ban reason is personal which should never happen, personal and staff issues should remain separate. I think I do a lot for the community, with CTFs and [youtube](https://www.youtube.com/channel/UCxWhMEGfFTFfUFWVbwseFxA) and stuff, and my ban reason is almost entirely issues that happened almost a year ago. The mod team has changed a lot since I was banned and I hope the new mods and admins can actually look at the issue and make a reasonable and explained decision.

**Comment by DefinitelyNotDave** [comment]
Someone screenshot/archive that before it gets deleted.

**Comment by Bentechy66** [comment]
> Someone screenshot/archive that before it gets deleted.

Already done

**Comment by actuallynotdave** [comment]
So my alt mysteriously cannot respond to this issue anymore, shame I have a mail server. I'd like to point out how beano's silence is indicative of the issue here and that this is not a him deciding thing as much as it is a staff deciding thing.

**Comment by actuallynotdave** [comment]
If beano recognises that wording from a certain staff chat conversation we had then he'll understand that he's become that which he swore to destroy.

**Comment by DillFletch** [comment]
i support dave

yes

**Comment by JuliaScythe** [comment]
I have no idea about the circumstances surrounding Dave and Collm and all that, I had left the server during that time, but surely we can forgive someone who (as far I can see) has grown up and clearly had an investment in the community. At the very least, the fact that Dave can be bothered to create all these alts shows that he still cares to an extent. This is a community about learning, so why shouldn't learning to be better behaved be part of that?

I know this server is big, and moderating is hard, and somebody is gonna hate you whatever you do, but If the mods are not gonna even consider the even slightly controversial issues raised in the repo, what is the point of it?

**Comment by Little-Green-Guy** [comment]
I think the introduction of temporary bans would be a good idea, as the jump from mute to permanent ban is quite a large one. The idea of unbanning all bans after a certain long period of time is an interesting one, maybe worth a shot, but it would probably be worth having more severe punishments after an unban due to trolls who dont care about the rules of the server.
I know there are sometimes requests to allow everyone to read #logs, which are rejected due to there maybe being deleted messages that were deleted for a reason, which is completely reasonable, but what about a #warn-logs as seen on TMHC?

**Comment by ThisIs0xBC** [comment]
I fully support the #UnbanDave movement and will continue to support it until the mods come to their senses and Beano drops the stupid grudge and authorises the unban.
+1 rep for Dave

**Comment by Little-Green-Guy** [comment]
cant comment too much on dave as i wasnt around, but from some of the discussions ive seen, the reason for not unbanning does seem to be more of a grudge than an actual reason.

Having a policy of unbanning everyone after a few months would solve it, but could also bring along its own problems.

**Comment by actuallynotdave** [comment]
> I have no idea about the circumstances surrounding Dave and Collm and all that, I had left the server during that time, but surely we can forgive someone who (as far I can see) has grown up and clearly had an investment in the community. At the very least, the fact that Dave can be bothered to create all these alts shows that he still cares to an extent. This is a community about learning, so why shouldn't learning to be better behaved be part of that?

Of course I care about the community, I was owner and root for a while and have been a large part of how the community has grown. It hurts to see the issues with the community, I know I could have done more when I was owner to make sure that the staff team couldn't go downhill again and I really regret not doing that. Similarly, I regret most of what happened between October and February, it was completely stupid and caused way too many issues. I still talk to a decent amount of the people in the community, I help make ractf which started as a cyberdiscovery community, of course I want to be involved with it. And I'm a very different person to who I was almost a year ago, I was going through a weird time in my life that I look back on like "wtf was I thinking"(this isn't directed to the person I was talking to at the time, my life in general was weird at that time and I didn't have a clue what I was doing), I'm not trying to say I wasnt at fault, I completely was but I've moved on from that.

> I know this server is big, and moderating is hard, and somebody is gonna hate you whatever you do, but If the mods are not gonna even consider the even slightly controversial issues raised in the repo, what is the point of it?

Ultimately, the staff team needs to be able to deal with controversial issues. Having a coup to remove the previous owner and move server was much more controversial and dramatic than any of the issues that are being raised today. The staff team needs to be more effective at dealing with issues, and not let personal issues get in the way. Cd is a big community and it needs to be moderated as such, unfortunately it seems like the staff are less organised then they were when I was owner and you cannot run a server like that. I have a lot more to say about the staff team and how well it's run but I won't because it's information I've heard from current and past staff members(if any root wants to have a discussion, please dm me). I like most of the staff but as a team, a lot needs to change.

> The idea of unbanning all bans after a certain long period of time is an interesting one, maybe worth a shot, but it would probably be worth having more severe punishments after an unban due to trolls who dont care about the rules of the server.

Bans are hard to get right and it really varies case by case. Sometimes it's an active user that's gone a step too far and just needs it made clear that it's not acceptable, timed bans work for that. But in cases like mine, a short term ban wouldn't have helped, dabato got unbanned because staff thought he had changed, and I was told my unban would be in similar circumstances. This obviously hasn't happened. But for cases like mine or dabato, the staff should use their judgement for when they think an unban would be reasonable. I'd be very surprised if any staff members could actually come up with a good reason to keep me banned.

> I know there are sometimes requests to allow everyone to read #logs, which are rejected due to there maybe being deleted messages that were deleted for a reason, which is completely reasonable, but what about a #warn-logs as seen on TMHC? 

This has been suggested many times, it wouldn't take much effort for the staff. The last time I discussed this with a staff member was a few months ago when there was a problem with staff using moderation commands in private channels.

> I fully support the #UnbanDave movement and will continue to support it until the mods come to their senses and Beano drops the stupid grudge and authorises the unban.
> +1 rep for Dave

<3

> cant comment too much on dave as i wasnt around, but from some of the discussions ive seen, the reason for not unbanning does seem to be more of a grudge than an actual reason.
> 
> Having a policy of unbanning everyone after a few months would solve it, but could also bring along its own problems.

I addressed the ban thing earlier. I do agree it seems like Beano has a grudge, I hope I'm wrong because that's no way to run a server but I don't think I am. If any staff want to give a good reason why I'm still banned, DM me or respond to this issue, ignoring it won't fix the problem and just makes the community more unhappy.

**Comment by Little-Green-Guy** [comment]
> good reason to keep me banned.

I think a reason could be they dont believe you have changed, and that the same issues may arise (this may be completely inaccurate or impossible, I dont know the nature of the issues), and ultimately this is hard to judge.
But I think unbanning more often/using more timed bans would be beneficial. In cases like yours, it seems (to me at least) that you probably have changed, and in other cases, people either wouldnt bother rejoining, or they would have learnt after their ban period. In the case of cowtickle, for example, he was banned quickly after joining, so probably didnt have much knowledge of what was acceptable (although he should have made more of an effort to read readme), and was given no warning that it wasnt acceptable. I think he definitely wont be making the same mistake, so there isnt really a reason to keep him banned either.

**Comment by ThisIs0xBC** [comment]
Another reason for unbanning, what troll or timewaster is going to go to so much effort to get unbanned? If Dave hadn't changed, he wouldn't have spent so much time meticulously picking apart, analysing and responding to people's comments. It shows he truly cares and wants to be co-operative and a valuable member of the community.

**Comment by ThisIs0xBC** [comment]
In addition to my previous comment, maybe a ban appeals section that is public and can be commented on by other server members (and where the moderators post their decisions and reasoning publicly) could help. It would allow banned users to say their peace and give their reasons why they think they should be unbanned and gives active users a place to discuss the banned member also. I think this could prove very beneficial to the server if implemented properly.

Hopefully that made sense ^, I wrote it mid maths lesson in like 3 mins

**Comment by DillFletch** [comment]
just unban him ffs

**Comment by Little-Green-Guy** [comment]
can we have some interaction with the staff?
Like, have they discussed it yet? Did they discuss the points mentioned here? Was there an outcome to the discussions? Are they going to have further discussions?
It kind of defeats the point of meta if the staff just ignore certain issues, or discuss it briefly but dont tell the rest of the server.

**Comment by Little-Green-Guy** [comment]
Having reviewed the situation (although I am aware that it is only one side), it all seems a little petty.
Of course dave made a mistake, and I believe he has acknowledged that, but nothing really permanent ban worthy...
I think to avoid this, I really do thing that temporary bans could help. It would allow for another level of punishments, and I think even a general amnesty on bans as tref suggested (although I think its been removed) could help, especially in daves situation, helping avoid perhaps unfair grudges held. Of course, bans may need to be reapplied, and this wont help in all cases, and in some cases it may hinder, however these should not be used as a reason to not introduce them, as every case and situation it different, that's why we have this whole inconsistency problem.
Honestly, I dont know why I'm bothering, the staff wont respond or act, especially on this issue.

**Comment by lightspeedana** [comment]
Right, I think it's time this silence was broken, and the issue sorted once and for all, but first, there's a lot to say. 

After about a year of being a staff member, I've had to learn a few lessons the hard way, but one especially - whatever decision you make, you will upset someone. I personally have always taken softer stances and never wanted to hurt anyone, but this whole year of being a mod (and an admin) has definitely changed me in some way. I write this now realising that there will be people discontent with my response, but it's about time I took a harsher stance and grew up a little, and ended this issue on behalf of the whole team. 

It has also been a year since Dave was banned. For those of you who don't have the original ban message:
```
After numerous warnings about inappropriate and provocative comments, doxxing, alts and mention spam, you did not change your behaviour, even after you were specifically told you had one final chance. We tried giving you chances, but you kept pushing it. As a result, the staff team have decided to ban you from the server.
```
Dave himself has agreed multiple times that banning him at the time was the correct move. I did ask him tonight to clarify and he said `As I've said before, banning me was the correct move, if I was staff, I'd have banned me a lot sooner`. There were many things he said, did and even went on to do which were frankly awful, and I stand by banning him in November 2018 - I don't think anything we did was the wrong decision back then.

Nonetheless, a year has passed; and a lot has happened within it. Dave did all sorts of things in the aftermath which prompted us to have to sort out fires, #general consistently blew up, and we were branded as unwilling to compromise and, in a nutshell, authoritarian. In my honest opinion, Dave didn't do much to change our opinion on him - swearing at my friends on the team, being consistently rude to Beano and Shortcut (which I cannot forgive him for, it was really uncalled for and some things said were horrible) and generally being unwilling to compromise on his attitude towards us for clicking that one button in the GUI. 

It was only fairly recently that things flipped. Dave removed his alts and stopped being a complete pain in that respect, he actively involved himself in RACTF (a great project, but another thought entirely) and he even wrote a few letters to CD stating his reasons for things and explaining how he wouldn't rejoin even if unbanned. There are a few points in those letters however which need responding to. 

I would like to say a few things first about the people who I worked with back when Dave was banned. Whilst Shortcut is no longer staff, I have to say that Beano and Shortcut are two of my closest friends and I am sick and tired of people blaming both of them for anything and everything. Yes, they are both faces of the server, but that doesn't mean they are the only people ever making a decision. We work in a *team*, even now, and we made decisions as one whole group, discussing beforehand and making announcements or taking action as per. That is fundamentally how our team works, and it still does in the same way. Anything we do, no matter who does it, is done with the whole team's backing and we are here to support each other in that. Just because these two did announcements and acted on the team's behalf, does NOT mean that they were the only ones ever making decisions or pulling rank. That is not what we did, and it's not what we'll ever do. 

I honestly can't believe that I was put in this position of Root because of the fact that people were not content with **decisions I actually helped make** and they simply blamed it on others. It almost disgusts me that I could never really stand up for that, due to fear of burning bridges, but now I can say with no hesitation that I won't do that anymore.

Building on that point, please don't pre-empt our decisions or what we want to do - you can't say for sure that we're just going to maintain a stance after debate or that we're going to do something because we're "mean" or "have an agenda" or "work like a government". **_We aren't a government_**, and we listen to the community. Just because you don't see what we do behind the scenes to keep this server safe and friendly and running as a whole, doesn't mean you know what we're doing. We're completely democratic and receptive, but if we reject suggestions or ideas, it's because we've talked about them and decided against them for the better. 

Adding to that, **_WE ARE HUMAN._** We make mistakes, have lives outside of just Discord and most importantly, we are trying our best. We aren't bulletproof, it hurts sometimes when things are said about us, and **we are giving up our time** to make this server the best it can be. A few missteps along the way should never mean we are trying to hurt anything we have here - I love this community when it's appreciative of our efforts. I moderated through my GCSE year, Beano, BritMonkey, Tritoke and Shortcut through A-Levels, Bros through Year 12, and now, Tref, Denro, Fuze, Linus, Picapi and LITERALLY EVERY OTHER STAFF MEMBER EVER through some of the most important years of our lives! We have tried our best and sometimes, you appreciating that does make a huge difference.

Back to Dave, things have changed now. We have a new team of staff, and we've done this debate to death (with different people and in every manner and conclusion possible) and finally, we've decided on something that will work:

I feel like this message from Beano summarises what we've decided to do. 
```Whilst we believe that until now we have taken the right action, we feel that the time has come for us to offer the opportunity for all parties to resolve the mistakes of the past. Whilst he has previously stated his intentions to the contrary, if Dave does decide to rejoin, it will be under a probational basis, with a weakening of restrictions resulting from good behaviour.``` 

Dave, it's been a year, but I think it's time you returned on a probational basis. Don't break our rules, respect us, and contribute to the server and we'd be happy to make sure you remain. 

But I personally would like things to change. I want to feel like I'm doing something right - that I'm giving up time in order to make some kind of impact, to help people, and to learn a few things along the way. I am tired of being stuck in limbo, where no one understands why we do what we do and expects us to constantly give when all we ever do is get stabbed in the back for it. Being a moderator of a community is difficult, and I've certainly learnt that, but whilst we learn as a staff team and grow, the community has to appreciate what we do too. 

I am now speaking personally here, but there has been so much this year that it's almost hard to keep track. This server is one of the things I like to prioritise and help, but it's honestly draining to keep putting energy into something where my every action is scrutinised and I get sent emails telling me how horrible I am when all I have ever wanted to do is help.

I dislike ultimatums, but I can't keep going like this, where everything catches fire, my friends get hurt for trying to aid everyone, and I descend into a spiral of feeling like I can't do anything to make changes and that nothing we ever do will make a difference. There has to be a balance between good and bad for every side, and I refer back to how I opened this - **whatever decision you make, you will upset someone.** But if no one is ever pleased, it doesn't feel rewarding anymore to do a job you used to love doing.

That's why this issue needs to be sorted once and for all. This is more than just unbanning Dave and then putting worries aside because then something else will surface up - if I can't see change and our efforts aren't appreciated, **I will step down effective immediately.** I don't want it to come to that, but I need the server to realise that there are humans on the other side of a screen, and if you don't treat us like you'd treat anyone else decently, then we can and will just have to go. By all means, tell us how to improve! But do not expect us to be constantly here, on it, being superhuman. We are not, and I will step down and leave if my team isn't given the respect it deserves.

Thank you all for waiting for this response, and I hope this clears some major issues up, and hopefully, we can make this server a better place for everyone, even us staff. Dave, if you see this, please DM me.

**Comment by Bentechy66** [comment]
Big ups to the staff team

**Comment by ThisIs0xBC** [comment]
``but if we reject suggestions or ideas, it's because we've talked about them and decided against them for the better.``

That's the problem, you talk about it behind closed doors and then the community feel completely left out and and it makes it look like no debate or thought went into the decisions. The whole fucking point of the meta is for PUBLIC debate, not ones in fucking #staff

Excuse my French.

**Comment by Little-Green-Guy** [comment]
Other than the lack of acknowledgement of the outcome of this issue, I agree with Ben here, and I intend to make a meta issue on this as well as other issues, with proposed solutions as well.

**Comment by Ge0rg3** [comment]
jesus christ
