### ISSUE TITLE
Stop deleting criticism and jokes

### ISSUE THREAD

**Issue by Little-Green-Guy** [CyberDiscovery/meta#308]
# Stop deleting criticism and jokes

### *A description of the issue:*
after a message is deleted, sometimes a user comments on the deletion, possibly criticising it, joking about it, or asking for a reason. i have noticed several jokes and comments about a certain moderator deleting messages getting deleted. I dont know who deletes, them, but they are deleted, and they violate no rules.

In addition, there have been several occasions when asking why a message was deleted has been ignored or removed, and no reason given, even when linking or screenshotting the following message from ana on the topic:

> Otherwise, perfectly happy to explain anytime needed if asked for in specific cases

https://github.com/CyberDiscovery/meta/issues/301#issuecomment-554000382

### *Proposed Solution:*
stop doing it. give reasons when asked.

### *Additional Comments:*
none

**Comment by lightspeedana** [comment]
Deleting comments related to deletion is something I understand people are opposed to and I see no problem with us changing this. In terms of deleted messages themselves, those are often for a reason and hence we cannot compromise on that. Otherwise, I completely understand your point of view and there is scope for improvement. 

As for jokes, those are fine to remain but obviously, if they're offensive we retain the right to delete them. 

I hope this helps! 😄

**Comment by Little-Green-Guy** [comment]
yeah, often i am fine with the actual messages that are deleted, sometimes i send something knowing it will be deleted shortly. when im not fine with it i generally make that clear, and i am not fine with these cases where messages asking for reasons or commenting/joking about messages being deleted are deleted.

**Comment by lightspeedana** [comment]
That's entirely understandable - this is something that we'll work on as a team and hopefully we can resolve this issue - if not, I'll reopen it down the line. Sorry for the inconvenience :)
