### ISSUE TITLE
The whole server is a dictatorship and everything I do that is slightly out of line gets deleted or censored.

### ISSUE THREAD

**Issue by DillFletch** [CyberDiscovery/meta#312]
# Stop the Censorship, let the server be free.

### *A description of the issue:*
My past few issues were jokes however I am trying to convey an issue which has been bugging me and 60 other people in the scrabble server. I know this has been said before but maybe its time to listen.

### *Proposed Solution:*
Loosen up the server a little bit, set rules for mods on what they can and can't delete rather than making it a free for all. Mods seem to delete anything they personally dislike

### *Additional Comments:*
I would like to say that if the mods want to do nothing about this then feel free to close this issue, but it further damages how the mod team is portrayed, I have nothing against the mods personally but I just think that the server could be made better if it wasn't such a dictatorship power struggle.

Edit:
This is almost a continuation of #299 basically everyone except the mods agree.

**Comment by Little-Green-Guy** [comment]
i think a really comprehensive set of rules of what is allowed and what isnt and general punishment examples would be a great help. They would need to be enforced consistently and fairly, it almost seems like mods have a free for all on what they can do, and what punishment u get truly depends on what mods are online and their mood. You do consistently say that you try to improve consistency. _Making a set of rules like this will **help you** be consistent._ You say you're only human, which is true, so make smth like this will help.

the state of #299 implies to me that not much will happen as a result of this issue

who knows, maybe after a few more copies of this issue it will be done.

**Comment by ZomBMage** [comment]
Cleaning up spam isn't censorship

**Comment by DillFletch** [comment]
> Cleaning up spam isn't censorship

Yes, thats deletion and thats what mods are for, but there is a big level of censorship without explanation and I feel the server has gotten worse since Dave was first banned.

**Comment by installgentoolinux** [comment]
wow who cares it's a discord server. make a Matrix or XMPP server if it concerns you so much.

**Comment by alfiejfs** [comment]
was going to say something, but it appears @installgentoolinux has already said it!

**Comment by Little-Green-Guy** [comment]
ok i feel like i could clarify some things after dm'ing with fuze

imo, the main thing is example punishments being added to the rules. These may be ranges and can change depending on how repeated and serious it is etc.
then its enforcing it consistently, this is difficult, but with clear guidelines for mods it will be easier.
a more comprehensive set of rules is needed covering more situations so there arent situations not covered by the rules, less room for argument and inconsistency. of course, listing every possible thing not allowed is impossible, so they do need to be general, but they also need to be specific to an extent. finding this balance is hard.
and please be open to change. if people are complaining and suggesting something, put it to a meta poll! its great to see meta polls but more than once in a blue moon would be better. also please do be prepared to change rules and punishment if enough of the wider community wants it.

and probably most importantly, this is probably impossible to get right first time. maybe make drafts and create a meta issue for feadback, and put it into effect and see how it goes, adjusting as necessary. just because something is hard to change and get right the first time, doesnt mean it shouldnt be changed, and some change that isnt perfect is probably better than no change.

---
and as to avro and installgentoo, i would much rather a matrix/xmpp server, but everyone is here, on discord. discord is where the community is so i cant have the community on a platform no one is on.

**Comment by teamshortcut** [comment]
The audacity that mods should clean up you spamming this repo... truly the world is a cruel, cruel place for you.

**Comment by Little-Green-Guy** [comment]
yeah maybe the title should be changed...
but the actual issue is fair

**Comment by DillFletch** [comment]
> The audacity that mods should clean up you spamming this repo... truly the world is a cruel, cruel place for you.

it has nothing to do with that, i mean in the actual server. where did making the comment get you?

**Comment by ThisIs0xBC** [comment]
> > The audacity that mods should clean up you spamming this repo... truly the world is a cruel, cruel place for you.
> 
> it has nothing to do with that, i mean in the actual server. where did making the comment get you?

Yeah that's just shortcut being himself :/
He is literally useless/pedantic comments r us

**Comment by NilsIrl** [comment]
It would be nice to have some examples. Not necessarily with evidence but at least examples to see what *kind* of censorship you're talking about.

I haven't noticed any problems personally and think a mod log would be enough to solve the problem (so that at least what mods do is public).

**Comment by ThisIs0xBC** [comment]
@NilsIrl join the Scrabble server to see a community log of all stupid moderator actions (in our eyes), DM burnout Ben or little green guy for an invite

**Comment by ghost** [comment]
I'm bored, I'll chip in on this issue. As I've said however many times, the server's a total mess. But it's not too difficult to solve. There's issues from both sides, the staff team have been pretty ineffective but the community is also super toxic. The rules channel is useless, delete everything in there, write a new set of rules, that define clear boundaries and has a punishment system that doesn't depend on what the moderators feel like. You also need to have a catch-all, admin's discretion rule, however for that to be effective, you need reasonable people in your staff team that aren't going to abuse the hell out of it and I don't think the community has any faith in the staff team, but that's just a case of building up trust over time. TMHC has a decent rules system, and even if you can point out issues with it, its still a million times better than what you have currently. Overall I agree with littlegreenguy on this, draft some rules, let the community give you feedback. As for the message deleting thing, I really don't get wtf is going on. If you feel the need to delete messages from the same people, on countless separate occasions, you're either deleting way too much, or you need to start banning people. There was no reason to delete that many messages on new years for instance, it just causes the community to not like staff. Learn a thing or two from collm, if anyone remembers the .purge drama. The community is toxic, but that can be fixed with decent rules, even if 100% of your active members are toxic, if you ban them, eventually people who would've been active but were scared off by toxicity will start being active. And don't just care about toxicity to staff members, actually look at the rest of the server, rak got banned for being toxic to staff but there's people just as toxic that avoid staff and get away with it. Staff aren't special, treat toxicity towards anyone the same. I've been trying to avoid naming names but I'm going to have to for this. Beano, run your server or step down. There's been times where the server is melting down and you've posted and ran off. That's unacceptable for a moderator, let alone the owner. It's fine to have responsibilities, but you need to make a decision. Aurora and Shortcut resigned because they were too busy, regardless of my opinion of Shortcut, that was the right thing to do. The server is falling apart, the server we both spent a lot of time on, there was a time you'd stay up until 2 to sort server stuff out, now you won't even moderate, something needs to change. And to be clear, I have nothing against you anymore, I just need to say that. Also, in addition to having better rules for the community, get some rules and guidelines for staff. You take random people from the server, slap some privileges on them and expect them to moderate well? That's never going to work. If the staff have something to keep them in check, they'll be much more effective than they are currently. Also, for #staff, have some protocol to make decisions, stop letting people's suggestions be ignored, actually do something about them. If you actually wanted to improve the server, you'd take into account the feedback being given to you instead of ignoring it, nobody cares that you're all busy students, everyone is, but if you have time to complain about being a student, you have time to make a start on sorting the server out, even small changes over time would help it so much. I think that's all that I have to say, even if I've come across harsh, I want this server to improve, otherwise I wouldn't bother writing stuff like this.

**Comment by ZomBMage** [comment]
also to everyone saying "it's just a discord server", it's a bit more than that - it's a community.

I would have hoped you'd had the second braincell to notice that.

**Comment by NateKomodo** [comment]
I had my nickname set to "I support #312", and some random mod forced changed it, like wtf really? Leave me the fuck alone and stop proving the point of #312. I should be able to set my name to whatever I want that is SFW.

**Comment by ThisIs0xBC** [comment]
^ I'd like to also add that nothing in rules states that nicknames like that are not allowed. The only thing it says is "no offensive messages or nicknames (anything that a reasonable person may find offensive)". NOBODY and I shall repeat, NOBODY, will be offended by that nickname. Oh, and I beg you don't default back to the old faithful "the moderators can make choices based off of their judgement" and "the moderators decision is final" shite, there is nothing wrong with that nickname at all, you and I both know it.

**Comment by Little-Green-Guy** [comment]
Oh and on the same note, dont say something about not being a government or a democracy, when you do that, youre just shying away from any responsibility. You chose to become a moderator please act like one and take responsibility like one.

**Comment by AmusedNetwork** [comment]
I'd just close this and ignore it. It's only a Discord server. :)

**Comment by DillFletch** [comment]
> I'd just close this and ignore it. It's only a Discord server. :)

its a community m8

**Comment by DillFletch** [comment]
the mods just sit here and laugh, they really don't care, beano puts his special under discussion tag on the issue but he doesn't care because he knows really we can not do anything. its really selfish behavior and beano doesn't give a shit about us. you could say he is rather self-centered.

**Comment by SSAFuze** [comment]
@sm01man firstly I'd just like to say that I am confused why you seem to believe Beano is the sole moderator involved in this. We are a team, and are working as one to resolve this issue. I am fully aware you may elect to not believe this, but I can guarantee you that this 'under discussion' tag is true. We want to improve our community, but the best solutions aren't thought of overnight. We are actively working on certain proposals and we hope to get them out as soon as possible.

**Comment by NilsIrl** [comment]
Could we have a mod log?

**Comment by SSAFuze** [comment]
In what sense @NilsIrl?

**Comment by NilsIrl** [comment]
> In what sense @NilsIrl?

A channel that lists all (or at least a good subset of) the actions performed by the moderators.

**Comment by Little-Green-Guy** [comment]
similar to #warn-log in tmhc?
no one seemed opposed to it when i mentioned it in #283

**Comment by NilsIrl** [comment]
Wait there's a #logs channel?

**Comment by Little-Green-Guy** [comment]
#logs is staff only and because it includes deleted messages it will probably stay that way.

**Comment by NilsIrl** [comment]
Yes so basically what I'm asking is for #logs (or a subset of it) to be made public so we can monitor moderators and nothing happens in the dark.

**Comment by DillFletch** [comment]
> Yes so basically what I'm asking is for #logs (or a subset of it) to be made public so we can monitor moderators and nothing happens in the dark.

This would be a great step forward, they could add to the bot so that it also uploads to a channel called #public-logs except it doesn't show deleted messages, only who posted and deleted them.

**Comment by Little-Green-Guy** [comment]
i was thinking of something like #warn-log in tmhc where moderators manually write when people get warned, banned etc and a reason why, although actually i think your suggestion of maybe a redacted version of #logs which is made public may be better.

**Comment by NilsIrl** [comment]
Yes there should also be the reason why the people got banned because otherwise it's almost useless.
