### ISSUE TITLE
Make a skid blob

### ISSUE THREAD

**Issue by JX-CW** [CyberDiscovery/meta#328]
I feel like this is a missing part of the cd server as skids are integral to our community. I've made a rough draft and would like opinions on my art.
![image](https://user-images.githubusercontent.com/60669186/75392004-174d8c00-58e3-11ea-8235-80450371b8d4.png)

**Comment by Bottersnike** [comment]
I'm looking at that concept art and there's one big issue I'm seeing here... it's.. not square. Discord emojis (a) are perfectly square, and (b) have to look great at 22x22px.

**Comment by JX-CW** [comment]
@Bottersnike I feel this issue can be easily fixed by setting width and height to 22000px, and then scaling down by 1000x.

**Comment by Bottersnike** [comment]
At this point, I think this is satirical, but regardless I threw together a super-quick mockup of something that would probably be more plausible. Obviously the laptop is too small, and I did this in GIMP not Inkscape or Illustrator because I was lazy, so none of the lines are nice and crisp.
![kali](https://user-images.githubusercontent.com/7524553/75393211-77453200-58e5-11ea-99d1-183b36b84cca.png)

**Comment by Bottersnike** [comment]
Lmao I think we can close this as resolved :D

**Comment by JX-CW** [comment]
Awww he is so cute, love it
Perhaps not as emo as I would've liked but this is definitely a lovely addition to our server
