### ISSUE TITLE
Make Volcano a No Hint Zone™️🙅⛔⚔️

### ISSUE THREAD

**Issue by JX-CW** [CyberDiscovery/meta#341]
Too many people are getting past 3.4 on volcano base. This scares me. I propose we make volcano as a whole a No Hint Zone™️🙅⛔⚔️, so I have time to catch up to the 5.6 chads in peace.

**Comment by lightspeedana** [comment]
I completely agree on this being unfair, but unfortunately people will still give away solutions and hints in DMs and that's something out of our jurisdiction. Do you have an idea as to how to accomplish this on the server? :D

**Comment by JX-CW** [comment]
I do! Making #volcano a discussion only channel would be a start, and warning people who ask for help there, but I feel we could also extend this to people who flagbeg in DMs if screenshots are provided. Sadly there will never be a way to prevent willing people from giving out answers, but this is as close as we can reasonably get.

**Comment by ir0nstone** [comment]
I think one of the biggest problems is how many hints there are in the channel history, personally I don't think deleting it and recreating would necessarily be a bad thing.

**Comment by JX-CW** [comment]
Yeah sure, let me go extract all of those first, of course ;)

**Comment by ir0nstone** [comment]
Jokes aside, searching for the challenge number essentially gives you the answer for the vast majority. 4.4, for example, had the exact technique mentioned until I pointed it out to Linus and it got removed. Wouldn't be surprised if that became a bottleneck now.

**Comment by R0w4nS** [comment]
Weekly purge of all game channels?

**Comment by ir0nstone** [comment]
Why not. Or perhaps a similar thing to quotes where everyone can react with a specific emoji if they find it a spoiler and it gets removed. Or maybe when it gets marked as so by at least one person, after a day it automatically gets removed so people can't find it a month later.

**Comment by thebeanogamer** [comment]
Given that there is less than a week left on Game and Essentials, this issue feels like it has run its course. Obviously, if there is an extension and people still feel strongly about this, then we are happy to raise it again.

**Comment by RealJammy** [comment]
I think that the weekly purge of Cyberstart channels would be a good idea for next week,  and would literally only take a few seconds of a mod's day.  Furthermore,  the spoiler down vote system from earlier would also be a good idea as it can remove and punish people who spoil challenges

**Comment by Sh3llcod3** [comment]
@RealJammy I think considering that the intake for this year is pretty much over, purging for the last few days probably wouldn't be worth it, since, before a new year with assess begins, the old channels will be retired and new ones will be created as Game 2021 comes around.

The spoiler vote down system sounds good, but there will need to be set limit on how many downvotes it takes, to prevent abuse.

**Comment by R0w4nS** [comment]
Revive

**Comment by Skiller9090** [comment]
if we are making volcano only talk channel why dont we scan each message for two numbers in a row eg: 3 4 and if the message has the numbers in it referring to a level on volcano instead of being general then we delete the message stopping people getting advice on a certain level making it very hard to beg, furthermore we can also detect "l 3 c 4" or anything referring to a level. it is easy to do and makes it hard to beg or hint

**Comment by ir0nstone** [comment]
Not as if people will find a way around that. Purging the channels is probably the better option. Spoiler votes would be good too, I hate pinging mods for spoilers because it's so trivial yet there's no other way.
