### ISSUE TITLE
Unban Rak

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/meta#353]
Please

**Comment by RealJammy** [comment]
Personally, I believe that woa makes a very good point. As a beloved totem of our community, rak embodies the cyber discover spirit, and therefore should be unbanned. After 6 months of rak's banishment from the holy land, he has reformed as a man.

**Comment by woaisthisgit** [comment]
This is serious business jammy, no fooling around thank you.

**Comment by RealJammy** [comment]
I am not fooling around. Unbanning rak would be the best decision the staff team made since giving Denro root, rak should be unbanned from the commnunity.

**Comment by rag7** [comment]
I mean to be honest, I think he's changed and he'll be alright tho, but in the worst case scenario he's just gonna abuse the mods and you can permaban him again. People can change, and i think its fair to give him a second chance, he's been gone long enough.

**Comment by rak1507v2** [comment]
Just to add to this, I don't want to write a big cringy unban letter saying how much I've changed blah blah blah, I would hope other people's opinions of me show that. What I do want to say though, is there is a lot of CD stuff happening currently, and I find it very hard to keep up with everything without access to the discord server. This is one of the reasons I would highly appreciate it if I was unbanned, or even unbanned but remained permanently muted, just so I could use the server to get updates about CD and remain in the loop.

**Comment by ThisIs0xBC** [comment]
Revive, is this still under discussion? I hope it is.

**Comment by R0w4nS** [comment]
7 days to unban rak but 5 seconds to ban kazza? smh

**Comment by ThisIs0xBC** [comment]
3 days later, no response on whether it is still under discussion. It's so obvious the play the staff team are trying to make here, they're doing the age old "lets not respond for weeks and hope everyone forgets about it" hurr dur hee hee. That doesn't work. Stop trying it, and give us an update on what's happening with this issue.

**Comment by ThisIs0xBC** [comment]
5 days with no response and counting... I know you're reading this.

**Comment by woaisthisgit** [comment]
Well it's been 10 days and no sign of any discussion from the mods. Maybe rak hasn't changed and the reasons he was banned are still valid. Personally I think letting him join with a permamute would be a good compromise for both sides, but at the end of the day I'm not a mod, nor was I active at all when rak was in the server. It's fine if the mods have just decided to not unban rak, there's plenty of reasons on both sides, but if so would you mind just saying that you aren't going to unban him and closing the issue?

**Comment by lightspeedana** [comment]
I'm sorry for the radio silence thus far and understand this issue is of huge importance. I want to be able to be fair to Rak, the community, and the staff team in whatever formal response or solution we decide upon. I can't say for sure what will be decided, but things have been busy in the staff team lately and I want to make sure that whatever we say is fully thought out and we're able to give you a fully justified response. I'll hasten whatever decision we're coming to in the staff team as well to ensure this gets done 😄 thank you!

**Comment by lightspeedana** [comment]
As a staff team, we have agreed that Rak will not be unbanned at present. We have yet to see sufficient evidence that he or his behaviour has changed since he was initially banned from the server, and considering we gave him many chances during the period that he was on the server, we feel we cannot give him yet another one until he has shown a more compassionate side to his character and consciously behaves in an appropriate manner.

Rak was very recently banned from the CryptoHack server, and his behaviour on some other side servers show that he will not abide by the rules or behaviour we expect from members of this server. His past actions are also at times offensive and considering how we are trying to make this community more supportive and less toxic, we feel we cannot see a sufficient change in Rak at this point in time to allow him back on the server, where he may in fact jeopardise the friendly, supportive environment we are trying to achieve. 

Nonetheless, this is not to say that Rak will never be unbanned. If we see a change in his behaviour and more compassion in his actions down the line, our opinion may well change in the future if he re-appeals his ban. We are aware of his reasons of why he wishes to return to the server, and will be happy to allow him to rejoin if he sufficiently demonstrates a more community-aware side to his character.
