### ISSUE TITLE
Banned words - notification if used

### ISSUE THREAD

**Issue by JoshHeng** [CyberDiscovery/meta#365]
**Description of the issue**
I was talking on the general chat about Wynncraft by messages didn't seem to be sending. I tried to resend them and was subsequently muted by the bot. It turned out after that it was a banned word.

**Proposed solution**
I don't know if the bot can be configured to do this, but put a warning in the chat or DM the offender if a banned word is used so that they know it isn't just Discord being buggy.

**Comment by lightspeedana** [comment]
Yeah, I can agree that this needs to be more explicit - I think we could do a banned wordlist rework since Dyno often seems to automute for no reason and we need to unmute people manually when that happens, not knowing exactly what they did. But I entirely agree with this, and we'll look for a solution ASAP 😄

**Comment by rak1507v2** [comment]
mmm myes sensible suggestion getting suggested 19 days ago and nothing happening peak meta

**Comment by ghost** [comment]
Does dyno not let you set it that it sends a warning message when you need to “watch your language”

**Comment by n3bb** [comment]
gotta love mods not acting on meta issues

**Comment by seagull-pat** [comment]
Why not make a PR then?
