### ISSUE TITLE
Slightly rework how this is implemented to prevent meta being used instead of #polls

### ISSUE THREAD

**Issue by ghost** [CyberDiscovery/meta#9]
Whilst this new feature should work much better and is, the whole point of #polls was to be a spammy area for users. This can't happen due to the restriction on the trusted role which few people have, also due to the low position of #polls this is likely to be more widely used by people instead. 

If the rank of trusted as given out more widely or the restriction was lifted this would likely cause less issues.

**Comment by thebeanogamer** [comment]
_Shorter title plz_

**Comment by teamshortcut** [comment]
The entire reason we had to change the previous #suggestions system was because it was being abused. You misunderstand the point of #polls, it is absolutely not "to be a spammy area for users", and the exact reason it is tied to Trusted is so that we can remove it from people who use it as such, to allow for the people who actually want to poll stuff. However, to make this clearer I've edited the channel description of #polls.

**Comment by NateKomodo** [comment]
Time for a third revolution I think, everyone join the new server
